### GET USER5
GET https://jsonplaceholder.typicode.com/users/5
### GET USERS
GET https://jsonplaceholder.typicode.com/users
### GET todos
GET  https://jsonplaceholder.typicode.com/todos/

### GET catagory
GET http://localhost:8888/courses


### GET products
GET  http://localhost:8081/api/products

### GET 



